apiVersion: apps/v1
kind: Deployment
metadata:
  name: qamail-deployment
  namespace: qamail
  labels:
    app: qamail-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qamail-web
  template:
    metadata:
      labels:
        app: qamail-web
    spec:
      nodeSelector:
        <NODESELECTOR>
      containers:
      - name: qamail-web
        image: <QAMAILWEBIMAGE>
        env:
          - name: hostname
            value: <HOSTNAME>
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /home/app/qamail/settings.yml
          subPath: settings.yml
      - name: qamail-importer
        image: <QAMAILIMPORTERIMAGE>
        env:
          - name: hostname
            value: <HOSTNAME>
        volumeMounts:
        - name: config-volume
          mountPath: /home/app/qamail/settings.yml
          subPath: settings.yml
      - name: qamail-postfix
        image: <QAMAILPOSTFIXIMAGE>
        env:
          - name: hostname
            value: <HOSTNAME>
        volumeMounts:
        - name: config-volume
          mountPath: /etc/postfix/master.cf
          subPath: master.cf
        ports:
        - containerPort: 25
      - name: postgres
        image:  postgres:9.4.20
        env:
          - name: POSTGRES_USER
            value: qamail
          - name: POSTGRES_PASSWORD
            value: qamail
      volumes:
        - name: config-volume
          configMap:
            name: qamail-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qamail-config
  namespace: qamail
data:
  settings.yml: |
    app_root_directory: /home/app/qamail
    maildir: /home/app/Maildir/
    domain: <HOSTNAME>
    outgoing_mail_delivery_method: smtp
    smtp_port: 25
    smtp_server_hostname: localhost
    DB_host: localhost
    DB_username: qamail
    DB_password: qamail
    DB_name: qamail
    DB_encoding: utf8
    async_notifications: off
  master.cf: |
    smtp      inet  n       -       -       -       1       postscreen
    smtpd     pass  -       -       -       -       -       smtpd
    pickup    unix  n       -       y       60      1       pickup
    cleanup   unix  n       -       y       -       0       cleanup
    qmgr      unix  n       -       n       300     1       qmgr
    tlsmgr    unix  -       -       y       1000?   1       tlsmgr
    rewrite   unix  -       -       y       -       -       trivial-rewrite
    bounce    unix  -       -       y       -       0       bounce
    defer     unix  -       -       y       -       0       bounce
    trace     unix  -       -       y       -       0       bounce
    verify    unix  -       -       y       -       1       verify
    flush     unix  n       -       y       1000?   0       flush
    proxymap  unix  -       -       n       -       -       proxymap
    proxywrite unix -       -       n       -       1       proxymap
    smtp       unix  -       -       n       -       -       smtp
    relay     unix  -       -       y       -       -       smtp
            -o syslog_name=postfix/$service_name
    showq     unix  n       -       y       -       -       showq
    error     unix  -       -       y       -       -       error
    retry     unix  -       -       y       -       -       error
    discard   unix  -       -       y       -       -       discard
    local     unix  -       n       n       -       -       local
    virtual   unix  -       n       n       -       -       virtual
    lmtp      unix  -       -       y       -       -       lmtp
    anvil     unix  -       -       y       -       1       anvil
    scache    unix  -       -       y       -       1       scache
    postlog   unix-dgram n  -       n       -       1       postlogd
    maildrop  unix  -       n       n       -       -       pipe
      flags=DRhu user=vmail argv=/usr/bin/maildrop -d ${recipient}
    uucp      unix  -       n       n       -       -       pipe
      flags=Fqhu user=uucp argv=uux -r -n -z -a$sender - $nexthop!rmail ($recipient)
    ifmail    unix  -       n       n       -       -       pipe
      flags=F user=ftn argv=/usr/lib/ifmail/ifmail -r $nexthop ($recipient)
    bsmtp     unix  -       n       n       -       -       pipe
      flags=Fq. user=bsmtp argv=/usr/lib/bsmtp/bsmtp -t$nexthop -f$sender $recipient
    scalemail-backend unix	-	n	n	-	2	pipe
      flags=R user=scalemail argv=/usr/lib/scalemail/bin/scalemail-store ${nexthop} ${user} ${extension}
    mailman   unix  -       n       n       -       -       pipe
      flags=FR user=list argv=/usr/lib/mailman/bin/postfix-to-mailman.py
      ${nexthop} ${user}

---
apiVersion: v1
kind: Service
metadata:
  name: qamail-lb
  namespace: qamail
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "<HOSTNAME>."
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout : "1800"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "<ARNCERT>"
  labels:
    app: qamail-web
spec:
  selector:
    app: qamail-web
  ports:
  - name: ui
    port: 443
    targetPort: 80
    protocol: TCP
  - name: icmp
    port: 25
    targetPort: 25
    protocol: TCP
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
